services:
  - type: web
    name: whatsway-pro
    runtime: node
    rootDir: .
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node src/index.js
    envVars:
      - key: PORT
        value: 10000
      - key: CHANNEL_ID
        value: demo
      - key: NODE_ENV
        value: production
      - key: FREEIPAPI_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
